export const data = [
    {
        id: 1,
        rasm: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9llpRZyBsTqxGX7JSr3rw65FcUWdmVLVtiw&s",
        name: "Shirin Asqarova",
        fakultet: "Fiz-Mat",
        taskCompleted: 0,
        taskTotal: 2,
        deadline: "1 hafta",
        status: true,
        isRated: true,
        maxScore: 10,
        gradingTime: true,
    },
    {
        id: 2,
        rasm: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9llpRZyBsTqxGX7JSr3rw65FcUWdmVLVtiw&s",
        name: "Shirin Asqarova",
        fakultet: "Fiz-Mat",
        taskCompleted: 0,
        taskTotal: 2,
        deadline: "1 hafta",
        status: false,
        isRated: false,
        maxScore: 10,
        gradingTime: false,
    },
    {
        id: 3,
        rasm: "https://cdn.worldvectorlogo.com/logos/4x4-1.svg",
        name: "Azimjon Shukur",
        fakultet: "Fiz-Mat",
        taskCompleted: 1,
        taskTotal: 2,
        deadline: "1 hafta",
        status: true,
        isRated: true,
        maxScore: 10,
        gradingTime: true,
    },
    {
        id: 4,
        rasm: "",
        name: "Dilshod Raxmatov",
        fakultet: "Fiz-Mat",
        taskCompleted: 1,
        taskTotal: 2,
        deadline: "1 hafta",
        status: true,
        isRated: false,
        maxScore: 10,
        gradingTime: true,
    },
    {
        id: 5,
        rasm: "https://cdn.worldvectorlogo.com/logos/4x4-1.svg",
        name: "Dilshod Raxmatov",
        fakultet: "Fiz-Mat",
        taskCompleted: 2,
        taskTotal: 2,
        deadline: "1 hafta",
        status: true,
        isRated: true,
        maxScore: 10,
        gradingTime: true,
    },
    {
        id: 6,
        rasm: "",
        name: "Dilshod Raxmatov",
        fakultet: "Fiz-Mat",
        taskCompleted: 2,
        taskTotal: 2,
        deadline: "1 hafta",
        status: true,
        isRated: false,
        maxScore: 10,
        gradingTime: true,
    },
    {
        id: 7,
        rasm: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9llpRZyBsTqxGX7JSr3rw65FcUWdmVLVtiw&s",
        name: "Axtamov Ravshan",
        fakultet: "Ona-tili",
        taskCompleted: 0,
        taskTotal: 2,
        deadline: "1 hafta",
        status: false,
        isRated: true,
        maxScore: 0,
        gradingTime: true,
    },
    {
        id: 8,
        rasm: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9llpRZyBsTqxGX7JSr3rw65FcUWdmVLVtiw&s",
        name: "Axtamov Ravshan",
        fakultet: "Ona-tili",
        taskCompleted: 1,
        taskTotal: 2,
        deadline: "1 hafta",
        status: false,
        isRated: true,
        maxScore: 0,
        gradingTime: true,
    },
    {
        id: 9,
        rasm: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9llpRZyBsTqxGX7JSr3rw65FcUWdmVLVtiw&s",
        name: "Axtamov Ravshan",
        fakultet: "Ona-tili",
        taskCompleted: 2,
        taskTotal: 2,
        deadline: "1 hafta",
        status: false,
        isRated: true,
        maxScore: 0,
        gradingTime: true,
    },
    {
        id: 10,
        rasm: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9llpRZyBsTqxGX7JSr3rw65FcUWdmVLVtiw&s",
        name: "Axtamov Ravshan",
        fakultet: "Ona-tili",
        taskCompleted: 2,
        taskTotal: 2,
        deadline: "1 hafta",
        status: false,
        isRated: true,
        maxScore: 0,
        gradingTime: true,
    },
    {
        id: 11,
        rasm: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9llpRZyBsTqxGX7JSr3rw65FcUWdmVLVtiw&s",
        name: "Axtamov Ravshan",
        fakultet: "Ona-tili",
        taskCompleted: 2,
        taskTotal: 2,
        deadline: "1 hafta",
        status: false,
        isRated: true,
        maxScore: 0,
        gradingTime: true,
    },
    {
        id: 12,
        rasm: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9llpRZyBsTqxGX7JSr3rw65FcUWdmVLVtiw&s",
        name: "Axtamov Ravshan",
        fakultet: "Ona-tili",
        taskCompleted: 2,
        taskTotal: 2,
        deadline: "1 hafta",
        status: false,
        isRated: true,
        maxScore: 0,
        gradingTime: true,
    },
];
